import { factoryEnumsAnalytics } from "./factory-enums-analytics";

export const useEnumsFields = factoryEnumsAnalytics([
	"timestamp",
	"inn_company",
	"production_id",
	"taskid",
	"place_id",
	"place_name",
	"place_type",
	"device_id",
	"device_name",
	"device_type",
	"event_id",
	"event_name",
	"node_id",
	"node_name",
	"node_level",
	"data",
	"exported",
	"created",
	"name_production",
	"address_production",
	"id_company",
	"kpp_company",
	"name_company",
	"address_company",
	"descriptions_company",
	"phone_company",
]);
